### ISSUE TITLE
你好，我有问题求助！——REFUGE数据集的问题

### ISSUE THREAD

**Issue by LiYuXuan1999** [bai101315/MCDAU-Net#1]
我看您之前也在这个项目https://github.com/Bingyan-Liu/DDSC-NET/issues/1，下提出REFUGE数据集的问题，我这边也被拒绝了，请问能分享一下REFUGE数据集吗？

抱歉以这种方式打扰。

**Comment by LiYuXuan1999** [comment]
My email：lwcs@stu.xhu.edu.cn

**Comment by bai101315** [comment]
> 我看您之前也在这个项目[https://github.com/Bingyan-Liu/DDSC-NET/issues/1，下提出REFUGE数据集的问题，我这边也被拒绝了，请问能分享一下REFUGE数据集吗？](https://github.com/Bingyan-Liu/DDSC-NET/issues/1%EF%BC%8C%E4%B8%8B%E6%8F%90%E5%87%BAREFUGE%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E6%88%91%E8%BF%99%E8%BE%B9%E4%B9%9F%E8%A2%AB%E6%8B%92%E7%BB%9D%E4%BA%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%83%BD%E5%88%86%E4%BA%AB%E4%B8%80%E4%B8%8BREFUGE%E6%95%B0%E6%8D%AE%E9%9B%86%E5%90%97%EF%BC%9F)
> 
> 抱歉以这种方式打扰。

https://refuge.grand-challenge.org/， 这个是官方网站，你可以在上面下载

**Comment by LiYuXuan1999** [comment]
谢谢，我已经通过该渠道获取到了数据集。

 

发件人: ***@***.*** ***@***.***> 代表 bai101315
发送时间: 2024年1月23日 19:13
收件人: bai101315/MCDAU-Net ***@***.***>
抄送: LiBai1999 ***@***.***>; State change ***@***.***>
主题: Re: [bai101315/MCDAU-Net] 你好，我有问题求助！——REFUGE数据集的问题 (Issue #1)

 

我看您之前也在这个项目https://github.com/Bingyan-Liu/DDSC-NET/issues/1 <https://github.com/Bingyan-Liu/DDSC-NET/issues/1%EF%BC%8C%E4%B8%8B%E6%8F%90%E5%87%BAREFUGE%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E6%88%91%E8%BF%99%E8%BE%B9%E4%B9%9F%E8%A2%AB%E6%8B%92%E7%BB%9D%E4%BA%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%83%BD%E5%88%86%E4%BA%AB%E4%B8%80%E4%B8%8BREFUGE%E6%95%B0%E6%8D%AE%E9%9B%86%E5%90%97%EF%BC%9F> ，下提出REFUGE数据集的问题，我这边也被拒绝了，请问能分享一下REFUGE数据集吗？

抱歉以这种方式打扰。

https://refuge.grand-challenge.org/ <https://refuge.grand-challenge.org/%EF%BC%8C> ， 这个是官方网站，你可以在上面下载
